import { useState } from "react";

const levels = [
  { id: 0, label: "Level 0", title: "Absolute Beginner", color: "#4ade80", bg: "#052e16" },
  { id: 1, label: "Level 1", title: "Beginner", color: "#86efac", bg: "#14532d" },
  { id: 2, label: "Level 2", title: "Elementary", color: "#fde047", bg: "#422006" },
  { id: 3, label: "Level 3", title: "Intermediate", color: "#fb923c", bg: "#431407" },
  { id: 4, label: "Level 4", title: "Upper Intermediate", color: "#f87171", bg: "#450a0a" },
  { id: 5, label: "Level 5", title: "Advanced", color: "#c084fc", bg: "#3b0764" },
  { id: 6, label: "Level 6", title: "Upper Advanced", color: "#818cf8", bg: "#1e1b4b" },
  { id: 7, label: "Level 7", title: "Expert", color: "#38bdf8", bg: "#082f49" },
  { id: 8, label: "Level 8", title: "Upper Expert", color: "#22d3ee", bg: "#083344" },
  { id: 9, label: "Level 9", title: "Pro", color: "#f472b6", bg: "#500724" },
  { id: 10, label: "Level 10", title: "Elite Pro / Master", color: "#ff6b35", bg: "#1a0a00" },
];

const allCategories = [
  // ─── LEVEL 0 ───
  {
    level: 0,
    id: "c00",
    name: "C++ Syntax & Program Structure",
    count: 120,
    problems: [
      "Hello World program", "#include, using namespace std", "main() function anatomy",
      "Single-line & multi-line comments", "Semicolons and statement termination",
      "Whitespace and indentation rules", "Case sensitivity", "Identifiers & naming rules",
      "Keywords list & usage", "Basic input with cin", "Basic output with cout",
      "endl vs \\n", "Multiple variables on one line", "Chained cout statements",
      "Reading multiple inputs", "Program compilation with g++", "Common compile errors",
      "Linker errors vs compile errors", "Warnings and how to fix them",
      "Using -Wall flag", "Code blocks and braces", "Nested braces",
      "Scope basics with braces", "Blank lines and readability", "Code formatting standards",
      "Literal values (numbers, strings)", "String literals with quotes",
      "Escape sequences (\\n, \\t, \\\\)", "Raw string literals R\"(...)\"",
      "Unicode basics", "ASCII values", "char literals with single quotes",
      "Printing special characters", "Tab stops with \\t", "printf vs cout",
      "scanf vs cin", "puts() and gets() legacy", "iostream header",
      "cstdio header", "Including multiple headers", "Header file purpose",
      "Compilation steps overview", "Preprocessor directives", "#define basics",
      "Macro constants", "Conditional compilation #ifdef", "#pragma once",
      "Include guards", "Multiple source files concept", "Object files (.o)",
      "Linking explained", "argc and argv basics", "Command-line arguments printing",
      "Return 0 meaning", "Non-zero return codes", "EXIT_SUCCESS / EXIT_FAILURE",
      "Program entry/exit flow", "Debugger basics (gdb intro)", "Breakpoints concept",
      "Stepping through code", "Print-based debugging", "cerr for error output",
      "clog for logging", "flush output buffer", "std::endl flushing",
      "Buffered vs unbuffered output", "Reading entire line with getline",
      "Whitespace in getline", "cin.ignore() usage", "cin.clear() usage",
      "Input failure states", "Numeric input validation basics",
      "Type mismatch in input", "Overflow on small types",
      "Garbage values without initialization", "Undefined behavior intro",
      "Stack memory concept (simple)", "Static vs automatic storage basics",
      "Global variables basics", "Local variables basics",
      "Variable lifetime basics", "Block scope vs file scope",
      "Forward declarations basics", "Function prototypes concept",
      "Simple function definition", "Calling a function",
      "Return value from function", "void functions",
      "Parameters vs arguments", "Pass by value basics",
      "Multiple return values (intro)", "Overloading intro (concept only)",
      "Inline concept (brief)", "constexpr intro", "auto keyword intro",
      "decltype intro", "nullptr intro", "NULL vs nullptr",
      "Basic boolean logic", "true/false literals",
      "Boolean output (0/1)", "Casting bool to int",
      "sizeof operator", "Addresses concept (&)",
      "Dereferencing concept (*)", "Basic struct definition",
      "Struct member access", "Struct initialization",
      "Simple enum definition", "enum class basics",
      "typedef basics", "using alias basics",
      "Namespaces concept", "std:: prefix meaning",
      "using namespace std risks", "Named namespace basics",
      "Anonymous namespace", "Nested namespace (C++17)",
      "One-definition rule basics", "Translation unit concept",
      "Build systems intro (Makefile basics)", "IDE setup (VS Code / CLion)",
      "Online compilers (Godbolt, replit)", "Compiler flags overview",
      "-O0 / -O2 / -O3", "-std=c++17 / c++20 flags",
      "Address sanitizer (-fsanitize=address)", "UBSan intro",
      "Static analysis basics", "clang-format intro",
    ],
  },
  {
    level: 0,
    id: "c01",
    name: "Data Types & Variables",
    count: 110,
    problems: [
      "int, float, double, char, bool", "short, long, long long",
      "unsigned types", "signed vs unsigned",
      "Type sizes with sizeof", "INT_MAX / INT_MIN constants",
      "FLT_MAX / DBL_MAX", "Overflow wrap-around (unsigned)",
      "Signed overflow UB", "Floating point precision issues",
      "0.1 + 0.2 != 0.3 explained", "NaN and infinity (float)",
      "isinf() isnan()", "std::numeric_limits<T>",
      "Fixed-width types (int32_t, uint64_t)", "<cstdint> header",
      "ptrdiff_t and size_t", "Implicit type conversion",
      "Explicit cast (C-style)", "static_cast<>",
      "reinterpret_cast<>", "const_cast<>",
      "dynamic_cast<>", "Narrowing conversions",
      "Brace-init prevents narrowing", "Integer promotion rules",
      "Usual arithmetic conversions", "Integral vs floating arithmetic",
      "Mixed-type expressions", "Char arithmetic",
      "wchar_t, char16_t, char32_t", "String vs char array",
      "std::string basics", "string length vs size",
      "Accessing string characters", "string concatenation",
      "String comparison", "String to int (stoi)",
      "String to double (stod)", "Int to string (to_string)",
      "std::stof, stol, stoul", "String find() method",
      "String substr()", "String replace()",
      "String insert() / erase()", "String empty() / clear()",
      "C-string (char array) basics", "strlen vs string::size",
      "strcpy / strncpy", "strcmp / strncmp",
      "strcat / strncat", "sprintf / snprintf",
      "atoi / atof legacy", "String literals and pointers",
      "const char*", "string_view intro (C++17)",
      "Structured bindings (C++17)", "Tuple basics",
      "pair<T1,T2>", "make_pair()",
      "tie() for tuple unpack", "Optional<T> (C++17)",
      "variant<T...> (C++17)", "any (C++17)",
      "Bitfield basics", "Union basics",
      "Anonymous union", "Alignment and alignof",
      "alignas specifier", "Padding in structs",
      "#pragma pack", "POD types",
      "Trivially copyable types", "Standard layout types",
      "Aggregate initialization", "Designated initializers (C++20)",
      "Uniform initialization {}", "Value initialization",
      "Default initialization", "Zero initialization",
      "Copy initialization", "Direct initialization",
      "List initialization", "Brace elision",
      "Narrowing in initializer lists", "constexpr variables",
      "const vs constexpr", "consteval (C++20)",
      "constinit (C++20)", "inline variables (C++17)",
      "thread_local storage", "volatile keyword",
      "register keyword (deprecated)", "extern declaration",
      "Linkage: internal vs external", "One definition rule",
      "Tentative definitions (C)", "Multiple definitions error",
      "Redeclaration vs redefinition", "Forward declare struct",
      "Incomplete types", "Opaque pointer pattern",
      "Type aliases with using", "Template type aliases",
      "auto type deduction rules", "decltype(auto)",
      "CTAD (Class Template Arg Deduction)", "Concepts intro (C++20)",
      "requires clause basics", "Type traits overview",
      "is_integral<T>", "is_floating_point<T>",
      "is_same<T,U>", "remove_const<T>",
      "add_pointer<T>", "conditional<B,T,F>",
    ],
  },

  // ─── LEVEL 1 ───
  {
    level: 1,
    id: "c10",
    name: "Control Flow & Loops",
    count: 115,
    problems: [
      "if / else if / else", "Nested if statements",
      "Dangling else problem", "Switch-case statement",
      "switch fall-through", "switch with enum",
      "Ternary operator ?:", "Nested ternary (anti-pattern)",
      "while loop", "do-while loop",
      "for loop", "Range-based for loop",
      "Range-for with index trick", "Infinite loop patterns",
      "break statement", "continue statement",
      "goto (and why to avoid)", "Loop unrolling concept",
      "FizzBuzz", "Sum 1 to N",
      "Factorial (iterative)", "Fibonacci (iterative)",
      "Prime check", "Sieve of Eratosthenes",
      "GCD (Euclidean)", "LCM from GCD",
      "Count digits", "Reverse digits",
      "Palindrome number", "Armstrong number",
      "Perfect number", "Abundant number",
      "Sum of digits", "Digital root",
      "Power (iterative)", "Modular exponentiation",
      "Binary to decimal", "Decimal to binary",
      "Octal / Hexadecimal conversion", "Base conversion generic",
      "Leap year check", "Day of week calculation",
      "Number of days in month", "Time addition (HH:MM:SS)",
      "Matrix loop (row-major)", "Column-major access",
      "Star pattern (triangle)", "Inverted triangle",
      "Diamond pattern", "Floyd's triangle",
      "Pascal's triangle (print)", "Number pyramid",
      "Hollow rectangle pattern", "Spiral matrix print",
      "Loop invariant reasoning", "Off-by-one errors",
      "Index out of bounds", "Infinite loop debugging",
      "Early exit pattern", "Guard clauses",
      "Loop with multiple conditions", "Boolean flags in loops",
      "Counting with modulo", "Cyclic iteration",
      "Two-pointer in loops (intro)", "Sliding window intro",
      "Nested loop complexity", "Reducing O(n²) loops",
      "Loop fusion", "Loop fission",
      "Prefix sum with loop", "Running average",
      "Running max/min", "Mode of array in loop",
      "Frequency count with array", "Histogram in loop",
      "String reversal loop", "Palindrome string check",
      "Count vowels/consonants", "Caesar cipher loop",
      "ROT13", "String to uppercase/lowercase",
      "Remove spaces from string", "Count words in string",
      "Find substring manually", "Replace char in string",
      "Compress string (run-length)", "Expand compressed string",
      "Anagram check (sort approach)", "Isomorphic strings",
      "Longest run of character", "Most frequent character",
      "String rotation check", "Shift string by k",
      "Toggle case", "Title case conversion",
      "Trim leading/trailing spaces", "Tokenize by delimiter",
      "Count specific char", "Unique chars in string",
      "Remove duplicates in string", "Interleave two strings",
      "Merge sorted strings", "Longest common prefix (loop)",
      "atoi implementation", "itoa implementation",
      "strtol manual implementation", "Number formatting with commas",
      "Scientific notation parse", "Binary string to int",
      "Hex string to int", "IP address parse & validate",
      "Roman numeral to int", "Int to Roman numeral",
      "Expression evaluation (basic)", "Check balanced brackets",
      "Convert infix to prefix (intro)", "Luhn algorithm",
      "Checksum calculation", "CRC concept",
    ],
  },
  {
    level: 1,
    id: "c11",
    name: "Functions & Recursion",
    count: 120,
    problems: [
      "Function declaration vs definition", "Return types",
      "void functions", "Multiple return values via reference",
      "Default parameter values", "Default params ordering rules",
      "Function overloading", "Overload resolution rules",
      "Ambiguous overloads", "Name mangling",
      "extern \"C\" linkage", "Inline functions",
      "constexpr functions", "consteval functions (C++20)",
      "Function pointers", "Typedef for function pointer",
      "using alias for function pointer", "Calling via function pointer",
      "Array of function pointers", "Callback pattern",
      "Passing functions to functions", "Returning function pointers",
      "std::function<>", "std::bind()",
      "Partial application with bind", "Lambda expressions",
      "Lambda capture by value", "Lambda capture by reference",
      "Generic lambdas (C++14)", "Lambda in algorithms",
      "Immediately invoked lambda", "Recursive lambda",
      "Factorial (recursive)", "Fibonacci (recursive)",
      "Sum of array (recursive)", "Power (recursive)",
      "GCD (recursive)", "Binary search (recursive)",
      "Tower of Hanoi", "Flood fill (recursive)",
      "Permutations of string", "Subsets of set",
      "Combinations nCr", "Generate parentheses",
      "Sudoku solver", "N-Queens problem",
      "Rat in a maze", "Word search in grid",
      "Letter combinations phone", "Palindrome partitioning",
      "Restore IP addresses", "Combination sum",
      "Combination sum II (duplicates)", "Subset sum check",
      "Count paths in grid", "Unique paths (recursive)",
      "Staircase problem (1/2 steps)", "Min cost staircase",
      "Print all paths in maze", "Paint fill",
      "Boolean parenthesization", "Evaluate expression tree",
      "Tree traversal (recursive)", "Depth of tree (recursive)",
      "Reverse linked list (recursive)", "Merge sort",
      "Quick sort", "Recursive binary search",
      "Ackermann function", "Hofstadter sequence",
      "Mutual recursion (even/odd)", "Indirect recursion",
      "Tail recursion", "Tail call optimization",
      "Memoization basics", "Top-down DP with memo",
      "Stack overflow (too deep)", "Max recursion depth",
      "Iterative DFS vs recursive", "Convert recursion to iteration",
      "Call stack visualization", "Recursion tree analysis",
      "Recurrence relations (T(n)=2T(n/2)+n)", "Master theorem basics",
      "Divide and conquer paradigm", "Merge two sorted arrays",
      "Count inversions", "Closest pair of points",
      "Strassen matrix multiply concept", "Fast exponentiation",
      "Karatsuba multiplication concept", "Binary GCD",
      "Extended Euclidean algorithm", "Modular inverse",
      "Chinese Remainder Theorem basics", "Sieve segmented",
      "Prime factorization recursive", "Euler's totient",
      "Catalan numbers recursive", "Bell numbers",
      "Stirling numbers", "Partition numbers",
      "Derangements", "Inclusion-exclusion principle",
      "Pigeonhole principle problems", "Birthday paradox",
      "Pass by reference in recursion", "Accumulator pattern",
      "Continuation-passing style", "Trampolining pattern",
      "Mutual tail recursion", "Y-combinator concept",
      "Higher-order functions", "Currying in C++",
      "Functor objects", "Memoize wrapper",
      "LRU cache concept", "Fibonacci with matrix expo",
      "Nth root binary search (float)", "Newton's method sqrt",
      "Bisection method", "Fixed-point iteration",
    ],
  },
  {
    level: 1,
    id: "c12",
    name: "Arrays & Strings (Core)",
    count: 130,
    problems: [
      "1D array declaration & init", "Array size pitfalls",
      "Out-of-bounds access (UB)", "std::array<T,N>",
      "std::vector basics", "vector push_back",
      "vector at() vs []", "vector size vs capacity",
      "vector resize vs reserve", "2D vector",
      "2D array (C-style)", "Multidimensional arrays",
      "Array decay to pointer", "Passing array to function",
      "Array length tricks", "Sorted array check",
      "Linear search", "Binary search iterative",
      "Binary search on answer", "Lower bound / upper bound",
      "Find first/last occurrence", "Count occurrences (sorted)",
      "Insertion into sorted array", "Deletion from array",
      "Rotate array left/right", "Find rotation pivot",
      "Search in rotated sorted array", "Two sum (brute)",
      "Two sum (hash map)", "Two sum (two pointers)",
      "Three sum", "Four sum",
      "Max subarray (Kadane's)", "Max product subarray",
      "Min subarray (Kadane's variant)", "Subarray with given sum",
      "Subarray with 0 sum", "Longest subarray with sum k",
      "Merge two sorted arrays (in-place)", "Merge intervals",
      "Insert interval", "Non-overlapping intervals",
      "Meeting rooms I & II", "Minimum platforms",
      "Activity selection greedy", "Fractional knapsack",
      "0-1 Knapsack basics", "Partition equal subset sum",
      "Count subsets with sum", "Target sum (±)",
      "Move zeros to end", "Remove duplicates (sorted)",
      "Remove duplicates (unsorted)", "Remove element in-place",
      "Dutch national flag", "Sort 0s 1s 2s",
      "Sort by parity", "Sort by sign",
      "Wiggle sort", "Relative sort",
      "Custom comparator sort", "Sort structs",
      "Stable sort vs unstable", "Counting sort",
      "Radix sort", "Bucket sort",
      "Majority element (Moore's voting)", "Majority element II",
      "Find duplicate (Floyd's cycle)", "Find missing number",
      "Find two missing numbers", "First missing positive",
      "Single number (XOR)", "Two singles (XOR)",
      "Three singles", "Maximum consecutive 1s",
      "Minimum consecutive 0s", "Longest consecutive sequence",
      "Trapping rain water", "Container with most water",
      "Largest rectangle histogram", "Maximal rectangle in matrix",
      "Spiral order traversal", "Rotate matrix 90°",
      "Set matrix zeros", "Search in 2D matrix",
      "Search in sorted 2D matrix II", "Diagonal traversal",
      "Anti-diagonal traversal", "Layer-by-layer traversal",
      "Transpose matrix", "Matrix multiplication",
      "Prefix sum 1D", "Prefix sum 2D (range sum query)",
      "Difference array", "Range update range query",
      "Product array except self", "Stock buy sell (one tx)",
      "Stock buy sell (multiple tx)", "Stock with cooldown",
      "Stock with transaction fee", "Best time to buy (k tx)",
      "Jump game I (can reach end?)", "Jump game II (min jumps)",
      "Gas station problem", "Candy distribution",
      "Task scheduler", "Minimum cost to connect ropes",
      "Minimum operations to make equal", "Minimum swaps to sort",
      "Check if array is a permutation", "Find all anagrams in string",
      "Longest substring no repeat", "Longest substring k distinct",
      "Minimum window substring", "Substring permutation check",
      "Sliding window maximum", "Sliding window minimum",
      "Count distinct in window", "Average of subarrays size k",
      "Substrings with exactly k distinct", "Replace with rank",
      "Minimum number of arrows (balloons)", "Smallest range covering all lists",
    ],
  },

  // ─── LEVEL 2 ───
  {
    level: 2,
    id: "c20",
    name: "Pointers & Memory Management",
    count: 125,
    problems: [
      "Pointer declaration & initialization", "Address-of operator &",
      "Dereference operator *", "Null pointer (nullptr)",
      "Pointer arithmetic", "Pointer to array",
      "Array name as pointer", "Pointer to pointer (**)",
      "Pointer to function", "Const pointer vs pointer to const",
      "const T* vs T* const vs const T* const", "Void pointer (void*)",
      "Pointer casting", "Dangling pointer",
      "Wild pointer", "Pointer aliasing",
      "restrict keyword (C99 concept)", "Pointer comparison",
      "Pointer subtraction", "Pointer to struct member",
      "Arrow operator ->", "Dynamic allocation: new / delete",
      "new[] / delete[]", "malloc / calloc / realloc / free",
      "Operator new overload", "Placement new",
      "Memory leak detection", "Valgrind basics",
      "RAII pattern", "Destructor responsibility",
      "Rule of 3", "Rule of 5", "Rule of 0",
      "Copy constructor", "Move constructor",
      "Copy assignment operator", "Move assignment operator",
      "std::unique_ptr", "std::shared_ptr",
      "std::weak_ptr", "make_unique / make_shared",
      "Custom deleter", "Deleter with lambda",
      "shared_ptr reference count", "Circular reference problem",
      "Breaking cycles with weak_ptr", "enable_shared_from_this",
      "intrusive_ptr concept", "Object pools",
      "Arena allocator", "Stack allocator",
      "Pool allocator", "Custom allocator for STL",
      "std::allocator<T>", "Allocator traits",
      "Memory alignment", "Aligned allocation (aligned_new C++17)",
      "over-aligned types", "alignas / alignof",
      "std::launder", "Strict aliasing rule",
      "Type punning via memcpy", "Union type punning",
      "Bit manipulation via pointer", "Endianness check",
      "Big-endian vs little-endian", "Network byte order (htonl/ntohl)",
      "memcpy / memmove / memset / memcmp", "Overlapping memory regions",
      "Buffer overflow (concept & danger)", "Stack smashing",
      "Heap overflow", "Use-after-free",
      "Double free", "Address sanitizer output",
      "Garbage collection concept (Java comparison)", "Reference counting",
      "Mark-and-sweep concept", "Tracing GC concept",
      "Smart pointer internals", "Implementing shared_ptr from scratch",
      "Implementing unique_ptr from scratch", "Implementing vector from scratch",
      "Implementing string from scratch", "Copy-on-write string",
      "Small buffer optimization (SBO)", "Short string optimization",
      "std::span (C++20)", "std::mdspan (C++23)",
      "std::byte", "bit_cast (C++20)",
      "Casting pointers safely", "reinterpret_cast dangers",
      "Dynamic cast with polymorphism", "CRTP and static polymorphism",
      "Pointer to member (T::*)", "Calling via pointer-to-member",
      "std::mem_fn", "Pointer-to-member function",
      "Invocable concept", "std::invoke",
      "Function wrapper pattern", "Type-erased callable",
      "Pimpl idiom", "Opaque pointer",
      "Hidden implementation", "ABI stability",
      "Forward declaration for pimpl", "unique_ptr in pimpl",
      "Factory pattern with unique_ptr", "Observer with weak_ptr",
      "Singleton with static local", "Memory model basics",
      "Sequenced-before relation", "Observable side effects",
      "Sequence point rules", "Unspecified evaluation order",
      "Undefined behavior catalog", "Sanitizer-driven debugging",
      "Valgrind memcheck", "Valgrind massif (heap profiling)",
      "AddressSanitizer (ASan)", "MemorySanitizer (MSan)",
      "LeakSanitizer (LSan)", "UndefinedBehaviorSanitizer",
      "Perf profiling basics", "Cache-friendly memory access",
      "False sharing", "Struct of Arrays vs Array of Structs",
      "Prefetching (__builtin_prefetch)", "Branch prediction hints",
    ],
  },
  {
    level: 2,
    id: "c21",
    name: "OOP — Classes & Objects",
    count: 120,
    problems: [
      "Class vs struct (access default)", "Member variables",
      "Member functions", "this pointer",
      "Access specifiers (public/private/protected)", "Encapsulation",
      "Getters and setters", "Const member functions",
      "Mutable keyword", "Static member variables",
      "Static member functions", "Friend functions",
      "Friend classes", "Nested classes",
      "Local classes", "Anonymous classes",
      "Constructor types (default, param, copy)", "Constructor init list",
      "Delegating constructors (C++11)", "Inheriting constructors",
      "Explicit keyword", "Converting constructors",
      "Implicit conversions via constructor", "Destructor",
      "Virtual destructor", "Pure virtual destructor",
      "Operator overloading (+,-,*,/)", "Comparison operators (<=>)",
      "Spaceship operator (C++20)", "Stream operators << >>",
      "Subscript operator []", "Call operator ()",
      "Increment/decrement (pre/post)", "Conversion operator",
      "Assignment operator chaining", "Copy-and-swap idiom",
      "Inheritance basics (public)", "Protected inheritance",
      "Private inheritance", "Multiple inheritance",
      "Diamond problem", "Virtual inheritance",
      "Virtual base class constructor order", "MRO (Method Resolution)",
      "Method overriding", "override keyword",
      "final keyword (class & function)", "Covariant return types",
      "Base class pointer to derived", "Object slicing",
      "Dynamic dispatch (vtable)", "vtable layout",
      "vptr overhead", "Pure virtual functions",
      "Abstract classes", "Interface pattern",
      "CRTP (Curiously Recurring Template Pattern)", "Mixin via CRTP",
      "Static polymorphism vs dynamic", "Type erasure",
      "std::any for type erasure", "Polymorphic wrappers",
      "Strategy pattern", "Command pattern",
      "Observer pattern", "Decorator pattern",
      "Chain of responsibility", "Composite pattern",
      "Template method pattern", "Bridge pattern",
      "Flyweight pattern", "Proxy pattern",
      "Iterator pattern (custom)", "Visitor pattern",
      "State machine with classes", "Builder pattern",
      "Factory method", "Abstract factory",
      "Singleton (thread-safe)", "Prototype pattern",
      "Object pools (OOP)", "RAII wrapper class",
      "Handle-Body idiom", "Envelope-Letter idiom",
      "NVI (Non-Virtual Interface)", "Policy-based design",
      "Traits classes", "Tag dispatch",
      "Class invariants", "Assertion checks in constructor",
      "Exception in constructor", "Exception in destructor (danger)",
      "noexcept specifier", "noexcept operator",
      "Exception safety: basic, strong, nothrow", "Copy-on-write",
      "Lazy initialization", "Eager initialization",
      "std::optional as member", "Variant member",
      "Bitfield members", "Padding optimization",
      "Empty base optimization (EBO)", "[[no_unique_address]] (C++20)",
      "Class template basics", "Member templates",
      "Template specialization for class", "Partial specialization",
      "Variable templates", "Class with concepts (C++20)",
      "Constrained templates", "SFINAE with enable_if",
      "if constexpr in methods", "static_assert in class",
      "Reflection (manual/planned C++26)", "Serialization of objects",
      "JSON serialization pattern", "Binary serialization",
      "Comparison of classes (total order)", "Custom hash for class",
      "Class in unordered_map", "Class in std::set",
    ],
  },
  {
    level: 2,
    id: "c22",
    name: "STL Containers & Iterators",
    count: 130,
    problems: [
      "std::vector (all operations)", "std::deque",
      "std::list (doubly linked)", "std::forward_list",
      "std::array<T,N>", "std::string as container",
      "std::stack<T>", "std::queue<T>",
      "std::priority_queue (max-heap)", "std::priority_queue (min-heap)",
      "std::set<T>", "std::multiset<T>",
      "std::map<K,V>", "std::multimap<K,V>",
      "std::unordered_set<T>", "std::unordered_multiset",
      "std::unordered_map<K,V>", "std::unordered_multimap",
      "Choosing the right container", "Container complexity table",
      "Iterator concepts (input/output/forward/bi/random)", "Iterator invalidation rules",
      "begin() / end() / cbegin() / rbegin()", "std::distance / std::advance",
      "std::next / std::prev", "Iterator arithmetic",
      "Reverse iteration", "const_iterator usage",
      "Range-based for with iterators", "Custom iterator class",
      "Iterator adaptor (back_inserter)", "istream_iterator",
      "ostream_iterator", "move_iterator",
      "Insert iterator types", "counted_iterator (C++20)",
      "std::ranges::view", "Lazy ranges (C++20)",
      "View adapters (filter, transform)", "Range pipeline |",
      "take / drop / enumerate", "zip / zip_transform",
      "Sorted ranges algorithms", "Set operations on sorted ranges",
      "std::sort (Introsort)", "std::stable_sort",
      "std::partial_sort", "std::nth_element",
      "std::find / find_if / find_if_not", "std::count / count_if",
      "std::all_of / any_of / none_of", "std::for_each",
      "std::transform", "std::accumulate",
      "std::reduce (parallel)", "std::inclusive_scan / exclusive_scan",
      "std::inner_product", "std::adjacent_difference",
      "std::partial_sum", "std::fill / fill_n",
      "std::generate / generate_n", "std::iota",
      "std::copy / copy_if / copy_n", "std::move (algorithm)",
      "std::remove / remove_if", "Erase-remove idiom",
      "std::unique (for sorted)", "std::reverse",
      "std::rotate", "std::shuffle",
      "std::sample", "std::replace / replace_if",
      "std::swap / iter_swap / swap_ranges", "std::merge",
      "std::inplace_merge", "std::includes",
      "std::set_union / set_intersection / set_difference", "std::set_symmetric_difference",
      "std::min / max / minmax", "std::min_element / max_element",
      "std::clamp", "std::lower_bound / upper_bound",
      "std::equal_range", "std::binary_search",
      "std::is_sorted / is_sorted_until", "std::is_permutation",
      "std::next_permutation / prev_permutation", "std::heap ops",
      "make_heap / push_heap / pop_heap / sort_heap", "std::lexicographical_compare",
      "std::mismatch", "std::equal",
      "std::search / search_n", "std::starts_with / ends_with (C++20)",
      "Custom comparator with lambda", "std::less / std::greater",
      "std::greater<void> (transparent)", "std::hash specialization",
      "Custom hash function", "Collision handling concept",
      "Open addressing vs chaining", "Load factor and rehashing",
      "unordered_map reserve()", "Bucket count and max load factor",
      "Map emplace / try_emplace", "Map insert_or_assign",
      "Map merge (C++17)", "Map extract node (C++17)",
      "Multimap equal_range", "Set erase by iterator vs value",
      "Set lower/upper_bound", "Ordered vs unordered perf comparison",
      "Flat map (sorted vector of pairs)", "Boost flat_map concept",
      "Small vector optimization concept", "Inplace vector (C++26)",
      "std::span over container", "std::string_view over string",
      "Container adaptors internals", "Priority queue with custom struct",
      "Monotonic stack pattern", "Monotonic deque pattern",
      "Sliding window with deque", "Two-heap median",
      "K closest elements", "Kth largest element",
      "Top-K frequent elements", "Sort characters by frequency",
    ],
  },

  // ─── LEVEL 3 ───
  {
    level: 3,
    id: "c30",
    name: "Linked Lists",
    count: 120,
    problems: [
      "Singly linked list implementation", "Doubly linked list",
      "Circular linked list", "XOR linked list",
      "Insert at head/tail/position", "Delete by value/position",
      "Search in linked list", "Length of list",
      "Print list", "Print reverse (recursive)",
      "Reverse a linked list (iterative)", "Reverse (recursive)",
      "Reverse in groups of K", "Reverse between positions L and R",
      "Detect cycle (Floyd's)", "Find cycle start",
      "Remove cycle", "Length of cycle",
      "Intersection of two lists", "Check if palindrome",
      "Remove duplicates (sorted)", "Remove duplicates (unsorted)",
      "Remove Nth from end", "Middle of list",
      "Merge two sorted lists", "Merge K sorted lists",
      "Sort linked list (merge sort)", "Sort linked list (quick sort)",
      "Add two numbers (list digits)", "Multiply two lists",
      "Subtract two numbers (list)", "Add 1 to list number",
      "Swap nodes in pairs", "Swap every K nodes",
      "Rotate list right by K", "Flatten multilevel list",
      "Flatten sorted doubly nested", "Copy list with random pointer",
      "Clone graph via list", "Odd-even node rearrangement",
      "Segregate even/odd positions", "Move zeros to end (list)",
      "Partition list around x", "Sort list 0/1/2",
      "Intersection node value", "Check list is sorted",
      "Find Kth from end", "Find Kth from start",
      "Skip M delete N", "Delete without head pointer",
      "Delete all occurrences of value", "Delete all duplicates (keep unique)",
      "Remove nodes with greater right value", "Remove nodes not in range",
      "Merge in between lists", "Insert greatest common divisors",
      "Spiral order linked list", "Zigzag reorder",
      "Reorder list (L0→Ln→L1→Ln-1)", "Split list into two halves",
      "Split into k parts", "Merge alternating from two lists",
      "Interleave two lists", "List from array / array from list",
      "Convert BST to doubly linked list", "Convert binary tree to list",
      "Flatten binary tree to linked list", "LRU Cache implementation",
      "LFU Cache implementation", "Skip list basics",
      "Skip list search / insert / delete", "Skip list vs BST",
      "Unroll linked list (cache optimization)", "Self-organizing list",
      "Move-to-front heuristic", "Frequency-based order",
      "Josephus problem (list)", "Queue using two stacks",
      "Stack using queues", "Deque from scratch",
      "Priority queue from linked list", "Sorted insert in linked list",
      "Insert into circular sorted list", "Inplace merge sorted lists",
      "Difference of two lists", "Union of two sorted lists",
      "Intersection of two sorted lists", "Maximum twin sum",
      "Sum of nodes between zeros", "Maximum pair sum",
      "Double a number (list)", "Swapping nodes (not values)",
      "Nodes in even/odd positions swap", "Link nodes at k distance",
      "Node with next greater element", "Next larger node",
      "List memory layout", "Cache-unfriendly nature of lists",
      "std::list vs std::vector perf", "std::forward_list usage",
      "List splice()", "List unique()",
      "List remove() / remove_if()", "List sort() (stable)",
      "List merge() (sorted)", "List reverse()",
    ],
  },
  {
    level: 3,
    id: "c31",
    name: "Stacks & Queues",
    count: 115,
    problems: [
      "Stack using array", "Stack using linked list",
      "Stack using std::stack", "Stack using std::vector",
      "Queue using array (circular)", "Queue using linked list",
      "Queue using std::queue", "Deque using std::deque",
      "Priority queue implementation", "Min-stack (O(1) getMin)",
      "Max-stack", "Two-stack queue",
      "Two-queue stack", "Stack with increment operation",
      "Queue with max operation", "Circular buffer",
      "Ring buffer for streaming data", "Monotonic stack intro",
      "Next greater element I", "Next greater element II (circular)",
      "Next smaller element", "Previous greater element",
      "Previous smaller element", "Largest rectangle in histogram",
      "Maximal rectangle (matrix)", "Sum of subarray minimums",
      "Sum of subarray maximums", "Remove k digits (smallest)",
      "132 pattern detection", "Daily temperatures",
      "Online stock span", "Asteroid collision",
      "Score of parentheses", "Remove duplicate letters",
      "Smallest subsequence of distinct chars", "Remove all adjacent duplicates",
      "Remove all adj duplicates (k times)", "Decode string (k[str])",
      "Simplify Unix path", "Valid parentheses",
      "Check redundant brackets", "Minimum remove to valid parens",
      "Count valid parentheses substrings", "Longest valid parentheses",
      "Minimum add to make valid", "Balance parentheses",
      "Evaluate reverse polish notation", "Basic calculator I",
      "Basic calculator II", "Basic calculator III",
      "Implement queue using stacks (amortized)", "Design bounded blocking queue",
      "Design front/middle/back queue", "Circular queue design",
      "Sliding window max (deque)", "Sliding window min",
      "K sliding window averages", "Max of all subarrays size k",
      "BFS using queue (graph)", "BFS level order (tree)",
      "ZigZag level order", "Level averages",
      "Level right side view", "Populating next right pointers",
      "Multi-source BFS", "0-1 BFS",
      "Dijkstra with priority queue", "Prim's with priority queue",
      "A* algorithm (priority queue)", "Huffman coding (priority queue)",
      "Merge K sorted arrays (heap)", "K-way merge",
      "Find median from data stream", "Sliding window median",
      "Top K frequent words", "Sort nearly sorted (k-sorted)",
      "Design Twitter (top 10 tweets)", "Task scheduler (queue)",
      "CPU scheduling FCFS/SJF", "Round-robin scheduling",
      "Print binary numbers 1 to N", "First negative in window",
      "Gas station circular queue", "Number of islands (BFS)",
      "Walls and gates BFS", "Rotten oranges BFS",
      "Shortest path binary matrix", "01 matrix (BFS)",
      "Pacific Atlantic water flow", "Snakes and ladders",
      "Jump game BFS variant", "Open the lock",
      "Word ladder I", "Word ladder II (all shortest)",
      "Minimum knight moves", "Sliding puzzle BFS",
      "Minimum steps to reach target (BFS)", "Minimum genetic mutation",
      "Alien dictionary (topological sort)", "Course schedule BFS",
      "Network delay time", "Cheapest flights within K stops",
    ],
  },
  {
    level: 3,
    id: "c32",
    name: "Hashing & Hash Tables",
    count: 110,
    problems: [
      "Hash function design principles", "Division method",
      "Multiplication method", "Universal hashing concept",
      "Perfect hashing concept", "Chaining (separate chaining)",
      "Open addressing (linear probing)", "Quadratic probing",
      "Double hashing", "Robin Hood hashing",
      "Cuckoo hashing", "Load factor and rehashing",
      "Hash table implementation from scratch", "Dynamic resizing",
      "Amortized cost analysis", "unordered_map internals",
      "Custom hash for struct", "FNV hash function",
      "DJB2 hash function", "MurmurHash concept",
      "CityHash / SipHash concept", "Rolling hash (Rabin-Karp)",
      "Polynomial rolling hash", "Anti-hash test (worst case)",
      "Bloom filter", "Count-min sketch",
      "HyperLogLog concept", "Consistent hashing",
      "Two sum (classic)", "Four sum with hash",
      "Subarray zero sum", "Longest subarray with sum k",
      "Count subarrays with sum k", "Count subarrays xor k",
      "Subarray equal 0s and 1s", "Longest equal 0s 1s",
      "Group anagrams", "Valid anagram",
      "Isomorphic strings (hash)", "Word pattern",
      "Ransom note", "Contains duplicate",
      "Contains duplicate within k distance", "Contains duplicate within value diff",
      "Happy number (cycle detect)", "Repeated DNA sequences",
      "Find all duplicates in array", "Find all disappeared numbers",
      "Intersection of two arrays", "Intersection of two arrays II",
      "Union of two arrays", "Common characters",
      "Unique number of occurrences", "Top K frequent elements",
      "Sort characters by frequency", "Degree of array",
      "Max points on a line (slope hash)", "Number of boomerangs",
      "Brick wall minimum cuts", "Employee importance BFS+hash",
      "Alien dictionary frequencies", "First unique character",
      "First recurring character", "Jewels and stones",
      "Destination city (hash)", "Determine if matrix rotated (hash)",
      "Check if N and double exist", "Count number of pairs",
      "Minimum index sum (two lists)", "Longest harmonious subsequence",
      "Continuous subarray sum (k*n)", "Longest arithmetic subsequence",
      "Longest geometric subsequence", "Equal row and column pairs",
      "Check if graph is bipartite (color hash)", "Check if paths exist (hash+union find)",
      "Count paths with given xor", "Largest number after digit swaps",
      "Minimum consecutive cards to pick up", "Max number of k-sum pairs",
      "Count good meals (power of 2 sum)", "Count pairs divisible",
      "Number of wonderful substrings", "Find the difference",
      "Missing number (hash)", "Roman to integer (hash)",
      "Decode the message (hash)", "Check if pangram",
      "Buddy strings", "Close strings",
      "Determine if two strings close", "Reorganize string",
      "Task scheduler with counts", "Minimum number of operations",
      "Bulls and cows", "Word frequency counter",
      "Index pairs of a string", "Design hashmap from scratch",
      "Design hashset from scratch", "Time-based key-value store",
      "LRU Cache (hash + DLL)", "LFU Cache (two hashmaps)",
      "Design in-memory file system", "Design phone directory",
    ],
  },

  // ─── LEVEL 4 ───
  {
    level: 4,
    id: "c40",
    name: "Trees & Binary Search Trees",
    count: 140,
    problems: [
      "Binary tree node structure", "Tree insertion",
      "Tree deletion", "Tree search",
      "Inorder traversal (recursive)", "Preorder traversal",
      "Postorder traversal", "Level order traversal",
      "Zigzag level order", "Vertical order traversal",
      "Boundary traversal", "Diagonal traversal",
      "Morris inorder traversal", "Morris preorder",
      "Iterative inorder", "Iterative preorder (two stacks)",
      "Iterative postorder", "Iterative level order",
      "Height of tree", "Depth of node",
      "Count nodes", "Count leaf nodes",
      "Count internal nodes", "Sum of all nodes",
      "Max node value", "Min node value",
      "Diameter of tree", "Width of tree (max level width)",
      "Check balanced tree", "Check complete tree",
      "Check perfect tree", "Check full binary tree",
      "Check identical trees", "Check mirror/symmetric",
      "Subtree check", "Path sum (root to leaf)",
      "All root-to-leaf paths", "Path sum II (all paths)",
      "Path sum III (any path)", "Max path sum",
      "Lowest common ancestor (BST)", "LCA (binary tree)",
      "LCA with parent pointer", "Distance between nodes",
      "Nodes at distance K", "Burning tree problem",
      "Time to burn tree from node", "Count nodes in range [L,R]",
      "Floor in BST", "Ceil in BST",
      "Predecessor in BST", "Successor in BST",
      "Kth smallest in BST", "Kth largest in BST",
      "Rank of element in BST", "BST from sorted array",
      "BST from sorted linked list", "BST from preorder",
      "BST from postorder", "Validate BST",
      "Convert BST to sorted DLL", "Convert BST to greater sum tree",
      "Merge two BSTs", "Two sum in BST",
      "Find pair with given sum in BST", "Closest value in BST",
      "Largest BST subtree", "BST to min heap",
      "Serialize / deserialize binary tree", "Serialize BST (compact)",
      "Construct from inorder + preorder", "Construct from inorder + postorder",
      "Construct from level order", "Recover BST (two swapped nodes)",
      "Trim BST to range", "Prune tree",
      "Flatten tree to linked list", "Right side view",
      "Left side view", "Top view",
      "Bottom view", "Sum of nodes at level K",
      "Count nodes at level K", "Nodes at odd levels vs even",
      "Parent array representation", "Children sum property",
      "Modify tree to children sum", "Check children sum",
      "BST iterator (inorder)", "BST iterator (reverse inorder)",
      "Two pointer on BST iterators", "Maximum width (using indices)",
      "Check BST with range", "Duplicate subtrees",
      "Unique BSTs (Catalan number)", "Generate all BSTs (n nodes)",
      "All possible FBTs", "All structurally unique trees",
      "AVL tree rotations", "AVL insert / delete",
      "Red-black tree properties", "RB insert concept",
      "Treap (BST + heap priority)", "Splay tree concept",
      "Scapegoat tree", "Weight-balanced tree",
      "B-tree structure", "B+ tree structure",
      "Persistent BST concept", "Order statistic tree",
      "Augmented BST (rank/select)", "Interval tree",
      "Segment tree basics (intro)", "Fenwick tree intro",
      "Euler tour technique", "Heavy-light decomposition intro",
      "Centroid decomposition intro", "Ternary tree",
      "K-ary tree", "Expression tree",
      "Trie intro (move to trie category)", "Huffman tree",
      "Cartesian tree", "Threaded binary tree",
      "Right-threaded vs full-threaded", "Inorder successor (threaded)",
      "Level order using queue", "Spiral using two stacks",
      "Reverse level order", "Count nodes in complete tree",
      "Delete leaves with value", "Max depth of N-ary tree",
      "Serialize N-ary tree", "Encode N-ary as binary",
      "Diameter of N-ary tree", "Sum root to leaf numbers",
    ],
  },
  {
    level: 4,
    id: "c41",
    name: "Graphs — Fundamentals & Traversal",
    count: 125,
    problems: [
      "Graph representation: adjacency matrix", "Adjacency list",
      "Edge list", "Implicit graph",
      "Weighted vs unweighted", "Directed vs undirected",
      "Simple graph vs multigraph", "Dense vs sparse",
      "BFS iterative", "BFS with levels",
      "DFS iterative (stack)", "DFS recursive",
      "Connected components (undirected)", "Connected components (directed=SCC)",
      "Number of islands (DFS)", "Number of islands (BFS)",
      "Number of islands (Union-Find)", "Max area of island",
      "Flood fill", "Count enclaves",
      "Number of closed islands", "Surrounded regions",
      "Pacific Atlantic water flow", "Making a large island",
      "Check bipartite (BFS)", "Check bipartite (DFS)",
      "Possible bipartition", "Graph coloring (2-coloring)",
      "Cycle detection undirected (DFS)", "Cycle detection undirected (BFS)",
      "Cycle detection directed (DFS)", "Cycle detection directed (coloring)",
      "Topological sort (DFS)", "Topological sort (Kahn's BFS)",
      "Course schedule I", "Course schedule II",
      "Parallel courses minimum semesters", "Build order (compile deps)",
      "Alien dictionary", "Sequence reconstruction",
      "Redundant connection (undirected)", "Redundant connection II (directed)",
      "Detect cycle with Union-Find", "Find eventual safe states",
      "Keys and rooms", "Path existence query",
      "All paths from source to target", "All paths source to target II",
      "Find if path exists", "Number of ways to reach destination",
      "Shortest path (unweighted BFS)", "Shortest path (Dijkstra)",
      "Shortest path (Bellman-Ford)", "Shortest path (SPFA)",
      "Negative cycle detection", "Shortest path (DAG)",
      "Floyd-Warshall APSP", "Johnson's algorithm concept",
      "Reconstruct path (parent array)", "K shortest paths concept",
      "Yen's K-shortest paths", "Bidirectional BFS",
      "A* search", "Greedy BFS (best-first)",
      "Network delay time", "Cheapest flights K stops",
      "Path with max probability", "Path with minimum effort",
      "Swim in rising water", "Minimum cost to connect all points",
      "MST: Kruskal's", "MST: Prim's",
      "MST: Borůvka's concept", "Second minimum spanning tree",
      "Maximum spanning tree", "MST with constraints",
      "Critical connections (bridges)", "Bridge finding (Tarjan)",
      "Articulation points", "Biconnected components",
      "Strongly connected components (Kosaraju)", "SCC (Tarjan)",
      "Condensation DAG", "2-SAT problem",
      "Euler path / Euler circuit", "Hierholzer's algorithm",
      "Hamiltonian path (brute)", "Hamiltonian cycle (backtrack)",
      "Traveling salesman (bitmask DP)", "TSP with memoization",
      "Graph isomorphism concept", "Canonical form of graph",
      "Degree sequence", "Handshaking lemma",
      "Trees are graphs (n-1 edges)", "Sparse table on tree (LCA)",
      "Binary lifting (LCA)", "Kth ancestor",
      "Distance between nodes (LCA)", "Level ancestor query",
      "Virtual graph / implicit BFS", "Grid as graph",
      "Word ladder BFS", "Minimum knight moves",
      "Snakes and ladders BFS", "Sliding puzzle BFS",
      "Open the lock BFS", "Minimum genetic mutation",
      "Jump game BFS", "Bus routes BFS",
      "Minimum obstacle removal", "Shortest grid path with teleport",
      "Multi-source BFS (matrix)", "0-1 BFS (0/1 weight edges)",
      "Dial's algorithm", "Shortest path in maze",
      "Count paths in DAG", "Longest path in DAG",
      "Minimum vertex cover concept", "Maximum independent set concept",
      "Maximum bipartite matching (Hopcroft-Karp intro)", "Hall's theorem",
    ],
  },

  // ─── LEVEL 5 ───
  {
    level: 5,
    id: "c50",
    name: "Dynamic Programming",
    count: 150,
    problems: [
      // Classic 1D
      "Fibonacci (memoization)", "Fibonacci (tabulation)",
      "Climbing stairs", "Min cost climbing stairs",
      "House robber I", "House robber II (circular)",
      "House robber III (tree)", "Delete and earn",
      "Jump game (DP)", "Jump game II (min jumps DP)",
      "Decode ways", "Decode ways II (with *)",
      "Coin change (min coins)", "Coin change II (count ways)",
      "Integer break", "Perfect squares",
      "Ugly number II", "Super ugly number",
      "Nth Tribonacci", "N-th Fibonacci variant",
      // Knapsack family
      "0-1 Knapsack", "Unbounded knapsack",
      "Fractional knapsack (greedy)", "Rod cutting",
      "Partition equal subset sum", "Count subsets with sum k",
      "Target sum (±1 assign)", "Last stone weight II",
      "Minimum subset sum difference", "Ones and zeros (2D knapsack)",
      "Profitable schemes", "Number of dice rolls",
      // Strings DP
      "Longest Common Subsequence", "LCS reconstruction",
      "Shortest Common Supersequence", "Longest Common Substring",
      "Edit distance (Levenshtein)", "Delete op for same strings",
      "Minimum ASCII delete sum", "Longest palindromic subsequence",
      "Longest palindromic substring", "Count palindromic substrings",
      "Palindrome partitioning (min cuts)", "Palindrome partitioning II",
      "Wildcard matching (* ?)", "Regex matching (. *)",
      "Interleaving strings", "Distinct subsequences",
      "Longest increasing subsequence (O(n log n))", "LIS count",
      "LIS reconstruction", "Longest decreasing subsequence",
      "Longest bitonic subsequence", "Number of LIS",
      "Longest divisible subset", "Russian doll envelopes",
      "Maximum sum increasing subsequence", "Minimum number of deletions for sorted",
      // Grid DP
      "Unique paths I", "Unique paths II (obstacles)",
      "Minimum path sum grid", "Maximum gold in grid",
      "Cherry pickup I", "Cherry pickup II (two robots)",
      "Triangle min path sum", "Dungeon game (reverse DP)",
      "Count paths with sum (grid)", "Minimum falling path sum",
      "Minimum falling path sum II", "Out of boundary paths",
      "Knight probability in chessboard", "Number of paths (k moves)",
      // Interval DP
      "Matrix chain multiplication", "Burst balloons",
      "Strange printer", "Remove boxes",
      "Minimum cost to cut stick", "Minimum cost to merge stones",
      "Optimal binary search tree", "Palindrome partitioning I (all parts)",
      "Minimum cost to repair edges", "Boolean parenthesization",
      // Tree DP
      "House robber III", "Diameter of binary tree (DP)",
      "Max path sum in tree", "Longest ZigZag in tree",
      "Binary tree cameras", "Sum of distances in tree",
      "Maximum product of splitted tree", "Count nodes equal to avg of subtree",
      "Distribute coins in tree", "Minimum time to visit subtree nodes",
      // Bitmask DP
      "TSP bitmask DP", "Minimum XOR sum assignment",
      "Shortest path visiting all nodes", "Stickers to spell word",
      "Can I win (bitmask game)", "Zuma game",
      "Count sets of friends", "Maximize score after N ops",
      // Stock / State machine DP
      "Stock I (one transaction)", "Stock II (unlimited)",
      "Stock III (two transactions)", "Stock IV (k transactions)",
      "Stock with cooldown", "Stock with fee",
      "Best team with no conflicts", "Max profit from jobs",
      // Digit DP
      "Count numbers with at most k digits", "Count numbers with digit sum S",
      "Count numbers without digit d", "Count numbers with all unique digits",
      "Numbers with repeated digits", "Count special numbers",
      "Digit DP template", "Non-decreasing digits",
      // DP + Data Structures
      "Longest subarray with constraints (DP+deque)", "DP on segment tree",
      "Kadane as DP", "DP with binary search (patience sort)",
      "DP on trie", "DP on graph (shortest/longest)",
      "DP on DAG", "DP with SOS (sum over subsets)",
      // Probability DP
      "Knight probability", "New 21 game",
      "Soup servings", "Dice roll simulation",
      "Stone game I-V", "Predict winner",
      "Can I win", "Nim game",
      "Flip game II", "Chalkboard XOR game",
    ],
  },
  {
    level: 5,
    id: "c51",
    name: "Heaps, Priority Queues & Advanced Sorting",
    count: 110,
    problems: [
      "Binary heap property", "Max-heap vs min-heap",
      "Heap array representation", "Heapify (sift-down)",
      "Build heap O(n)", "Heap insert (sift-up)",
      "Heap extract-max/min", "Heap delete arbitrary",
      "Heap increase/decrease key", "Heap sort",
      "K largest elements", "K smallest elements",
      "Kth largest in stream", "Kth smallest in stream",
      "Top K frequent elements (heap)", "Top K frequent words",
      "Sort nearly sorted (k-sorted array)", "Merge K sorted arrays",
      "Merge K sorted linked lists", "Smallest range covering K lists",
      "Find median from data stream", "Sliding window median",
      "Running median", "Median of stream (two heaps)",
      "K closest points to origin", "K closest points in stream",
      "Minimum cost to connect ropes", "Task scheduler (heap)",
      "Reorganize string (heap)", "Distant barcodes",
      "Find the most competitive subsequence", "Remove stones to minimize total",
      "Minimum number of refueling stops", "IPO (max capital)",
      "Maximum number of events (heap)", "Meeting rooms III",
      "Car pooling", "Single-threaded CPU",
      "Process tasks using servers", "Minimum time to finish jobs",
      "Reduce array size to half", "Sort characters by frequency",
      "Trapping rain water II (3D, heap)", "Swim in rising water",
      "Cut off trees for golf event", "Dijkstra with heap",
      "Prim's with heap", "Huffman coding",
      "Fractional cascading concept", "d-ary heap",
      "Fibonacci heap concept", "Brodal queue concept",
      "Pairing heap", "Leftist tree",
      "Skew heap", "Binomial heap",
      "Mergeable heap operations", "Persistent heap concept",
      "Heap with lazy deletion", "Soft heap concept",
      "Double-ended priority queue", "Min-max heap",
      "Counting sort deep dive", "Radix sort (LSD vs MSD)",
      "Bucket sort with distribution", "Flash sort",
      "American flag sort (in-place radix)", "Postman sort",
      "Bead sort concept", "Pancake sort",
      "Gnome sort", "Cycle sort",
      "Strand sort", "Library sort",
      "Timsort internals", "Introsort internals",
      "Smoothsort", "Tournament sort",
      "External merge sort", "Polyphase merge sort",
      "Replacement selection sort", "Sorting networks",
      "Bitonic sort", "Odd-even merge sort",
      "AKS sorting network", "Cache-oblivious sorting",
      "Sample sort (parallel)", "Parallel sort concepts",
      "Inversion count (merge sort)", "Count smaller after self",
      "Count of range sum", "Reverse pairs",
      "Global inversions local inversions", "Minimum number of swaps to sort",
      "Sort transformed array", "Wiggle sort II",
      "Largest number (custom sort)", "Maximum gap (radix/bucket)",
      "H-index I & II", "Relative ranks",
      "Sort list (heap)", "Patience sorting (LIS connection)",
      "External sort file (concept)", "Tournament tree (k-way merge)",
    ],
  },

  // ─── LEVEL 6 ───
  {
    level: 6,
    id: "c60",
    name: "Advanced Trees (Segment Tree, Fenwick, Trie, etc.)",
    count: 130,
    problems: [
      // Segment Tree
      "Segment tree build (sum)", "Point update / range query",
      "Range update / point query (lazy)", "Range update / range query (lazy)",
      "Segment tree with max/min", "Segment tree product",
      "Segment tree GCD", "Persistent segment tree",
      "Merge sort tree (offline queries)", "Fractional cascading",
      "Segment tree beats (Ji driver)", "Segment tree on strings",
      "Dynamic segment tree (coordinate compress)", "Implicit segment tree",
      "2D segment tree (range 2D query)", "Wavelet tree concept",
      // Fenwick Tree (BIT)
      "BIT point update prefix sum", "BIT range sum",
      "BIT 2D (2D prefix sums)", "BIT for inversion count",
      "BIT for kth element", "BIT range update point query",
      "BIT range update range query", "BIT order statistics",
      "Count smaller numbers after self (BIT)", "Count of range sum (BIT+compress)",
      "Reverse pairs (BIT)", "BIT on compressed coordinates",
      // Trie
      "Trie insert / search / startsWith", "Trie delete",
      "Count words in trie", "Longest prefix match",
      "Prefix search autocomplete", "Word search II (trie+DFS)",
      "Replace words with root", "Maximum XOR of two numbers (trie)",
      "Maximum XOR subarray", "Minimum XOR pair",
      "Sum of XOR of all pairs (trie)", "Count pairs with XOR in range",
      "Palindrome pairs (trie)", "Concatenated words (trie+DP)",
      "Design search autocomplete", "Stream of characters (trie)",
      "Implement magic dictionary", "Extra characters in string",
      "Distinct substrings count (trie)", "Lexicographically smallest subsequence",
      "Boggle solver (trie+DFS)", "Compressed trie (Patricia)",
      "Suffix trie", "Suffix array basics",
      "Suffix array construction (O(n log n))", "LCP array (Kasai's)",
      "Suffix automaton basics", "Aho-Corasick automaton",
      "KMP failure function", "Z-function (Z-array)",
      "Rabin-Karp rolling hash", "Boyer-Moore basics",
      // Sparse Table & RMQ
      "Sparse table RMQ (static, O(1) query)", "Sparse table build (O(n log n))",
      "Range GCD query", "Range LCM query",
      "Offline RMQ with sparse table", "LCA with sparse table",
      "Lowest common ancestor binary lifting", "Kth ancestor query",
      "Level ancestor query", "Euler tour + RMQ for LCA",
      // Disjoint Set Union (Union-Find)
      "Union-Find array representation", "Union by rank",
      "Union by size", "Path compression",
      "Union by rank + path compression", "Inverse Ackermann complexity",
      "Number of connected components", "Minimum spanning tree (Kruskal)",
      "Detect cycle (union-find)", "Redundant connection",
      "Accounts merge", "Most stones removed same row/col",
      "Satisfiability of equality equations", "Smallest string with swaps",
      "Number of islands (union-find)", "Remove max edges to keep bipartite",
      "Grate connectivity queries offline", "Dynamic connectivity offline",
      "Link-cut tree concept", "Offline LCA (Tarjan's offline)",
      // DSU advanced
      "Bipartite check with DSU", "Weighted DSU (parity check)",
      "DSU with rollback (offline)", "Parallel binary search + DSU",
      // Balanced BST
      "AVL tree rotations all cases", "AVL insert/delete balanced",
      "Red-black tree coloring rules", "RB insert rebalance",
      "RB delete rebalance", "Treap random priority",
      "Treap split/merge", "Treap implicit key",
      "Splay tree zig/zig-zig/zig-zag", "Splay access amortized",
      "Skip list probabilistic", "Skip list search/insert/delete",
      "Van Emde Boas tree concept", "Y-fast trie",
      "Cache-oblivious BST", "B-tree order m operations",
    ],
  },
  {
    level: 6,
    id: "c61",
    name: "Advanced Graph Algorithms",
    count: 120,
    problems: [
      "Dijkstra proof of correctness", "Dijkstra with decrease-key",
      "Dijkstra on sparse vs dense graphs", "Bellman-Ford proof",
      "Bellman-Ford negative cycle detection", "SPFA (Shortest Path Faster Algorithm)",
      "SPFA with SLF optimization", "Johnson's re-weighting",
      "Floyd-Warshall all pairs", "Floyd-Warshall path reconstruction",
      "Floyd-Warshall negative cycles", "Transitive closure",
      "A* heuristic requirements", "Consistent vs admissible heuristic",
      "IDA* (iterative deepening A*)", "Bidirectional Dijkstra",
      "Contraction hierarchies concept", "Hub labeling concept",
      // Network flow
      "Max flow min cut theorem", "Ford-Fulkerson (DFS augmenting)",
      "Edmonds-Karp (BFS augmenting)", "Dinic's algorithm",
      "Push-relabel algorithm", "Highest-label push-relabel",
      "Min-cost max-flow (MCMF)", "MCMF with SPFA",
      "MCMF with Dijkstra (potential)", "SSP (Successive Shortest Paths)",
      "Circulation with demands", "Feasible flow (lower bounds)",
      // Matching
      "Bipartite matching (Hungarian DFS)", "Hopcroft-Karp O(E√V)",
      "Minimum vertex cover (König's)", "Maximum independent set bipartite",
      "Maximum weight bipartite matching (Hungarian O(n³))", "Assignment problem",
      "General matching (Blossom algorithm concept)", "Stable matching (Gale-Shapley)",
      // SCC & 2-SAT
      "Kosaraju's SCC", "Tarjan's SCC",
      "SCC condensation DAG", "SCC applications (feedback vertex)",
      "2-SAT implication graph", "2-SAT solution extraction",
      "2-SAT with SCC", "3-SAT NP-complete (comparison)",
      // Bridges & Articulation
      "Bridges (Tarjan low-link)", "Articulation points",
      "Biconnected components (BCCs)", "Block-cut tree",
      "Bridge tree", "2-edge-connected components",
      "2-vertex-connected components", "Ear decomposition",
      // Euler & Hamiltonian
      "Eulerian path existence conditions", "Eulerian circuit Hierholzer",
      "Chinese postman problem (undirected)", "Route inspection directed",
      "Hamiltonian path (backtracking)", "Hamiltonian cycle NP",
      "TSP O(2^n * n) DP", "TSP approximation (2-opt)",
      "Christofides algorithm concept", "Metric TSP approximation",
      // Planar & special graphs
      "Planar graph (Kuratowski theorem concept)", "Four color theorem context",
      "Interval graph", "Chordal graph",
      "Perfect elimination ordering", "Cactus graph",
      "Functional graph (each node one outgoing edge)", "ρ-cycle in functional graph",
      "Successor array cycle detection", "Iterated function sequences",
      // Tree algorithms advanced
      "Centroid decomposition", "Heavy-light decomposition",
      "Virtual tree (auxiliary tree)", "Small-to-large merging",
      "DSU on tree (DFS with rollback)", "Sack (small-to-large dfs)",
      "Mo's algorithm on trees", "Path queries HLD + segment tree",
      "Point update path max HLD", "Subtree queries with Euler tour",
      "LCT (Link-cut tree) access", "LCT expose path",
      "LCT link / cut operations", "LCT aggregate on path",
      "Top tree concept", "ETT (Euler Tour Tree) concept",
    ],
  },

  // ─── LEVEL 7 ───
  {
    level: 7,
    id: "c70",
    name: "Templates & Generic Programming",
    count: 120,
    problems: [
      "Function template basics", "Class template basics",
      "Template type parameters", "Template non-type parameters",
      "Template template parameters", "Variadic templates (C++11)",
      "Parameter pack expansion", "Fold expressions (C++17)",
      "Template specialization (full)", "Template partial specialization",
      "SFINAE basics (enable_if)", "Substitution failure",
      "void_t detection idiom", "Detection idiom (is_detected)",
      "Tag dispatch pattern", "Overload sets and templates",
      "Template argument deduction rules", "CTAD (C++17)",
      "CTAD deduction guides", "Abbreviated templates (C++20 auto param)",
      "Concepts basics (C++20)", "requires expression",
      "requires clause", "Concept satisfaction",
      "Concept subsumption", "Concept-constrained functions",
      "Concept-constrained class", "Standard library concepts",
      "Projections in ranges", "Constrained algorithms",
      "Template metaprogramming (TMP) intro", "Compile-time factorial",
      "Compile-time Fibonacci", "Compile-time GCD",
      "Compile-time prime check", "Type list",
      "Type list operations (front/back/nth)", "Type map",
      "Tuple implementation from scratch", "Tuple get<N>",
      "Tuple apply()", "Tuple zip",
      "Integer sequence (std::index_sequence)", "std::make_index_sequence",
      "std::apply implementation", "std::integer_sequence tricks",
      "if constexpr for specialization", "constexpr if branching",
      "Type traits all std:: traits", "Custom type traits",
      "Trait inheritance CRTP style", "Reflection via traits",
      "Policy classes", "Policy-based data structures",
      "Mixin pattern (CRTP)", "Recursive inheritance",
      "Linear inheritance list", "Abstract policy interface",
      "Expression templates (lazy eval)", "ET for matrix add",
      "ET avoiding temporaries", "Eigen-style expression system",
      "Proxy objects", "Proxy for lazy evaluation",
      "Curiously recurring templates", "CRTP for static polymorphism",
      "CRTP interface injection", "CRTP counter",
      "Template factory pattern", "Type-safe builder",
      "Named parameter idiom", "Fluent interface template",
      "Phantom types", "Tagged types (strong typedef)",
      "Type-safe units (dimensional analysis)", "Boost.Units concept",
      "Meta-functions (unary/binary)", "Meta-function class",
      "Invocable meta-function", "Higher-kinded types (simulated)",
      "Template lambda (C++20)", "Generic lambda internals",
      "Polymorphic lambda", "Overload set as type",
      "std::overload (proposal pattern)", "Recursive variant visitor",
      "std::visit with lambdas", "Exhaustive variant match",
      "Concept-based overloading", "Requires requires",
      "Concept diagnostics", "Diagnostic messages with concepts",
      "Friend function template", "Template friend class",
      "Dependent names (typename/template)", "Two-phase name lookup",
      "ADL (Argument-Dependent Lookup)", "Koenig lookup",
      "Hidden friends idiom", "Namespace and ADL interactions",
      "Template instantiation on demand", "Explicit instantiation",
      "Extern template (C++11)", "Reducing compile times",
      "Pch with templates", "Module system (C++20) basics",
      "Module interface unit", "Module implementation unit",
      "Module partition", "Importing std module",
      "Reachability vs visibility in modules", "Module linkage",
      "Clang module map", "Coroutine as template (C++20)",
    ],
  },
  {
    level: 7,
    id: "c71",
    name: "Concurrency & Multithreading",
    count: 120,
    problems: [
      "Thread creation (std::thread)", "Thread join / detach",
      "Thread id", "hardware_concurrency()",
      "Mutex basics (std::mutex)", "lock_guard<>",
      "unique_lock<>", "shared_mutex (C++17)",
      "shared_lock (readers-writer lock)", "Recursive mutex",
      "Timed mutex (try_lock_for)", "Deadlock concept",
      "Deadlock avoidance (lock ordering)", "std::lock() for multiple",
      "std::scoped_lock (C++17)", "Livelock concept",
      "Starvation concept", "Priority inversion",
      "Condition variable basics", "wait() / notify_one() / notify_all()",
      "Producer-consumer with condition variable", "Bounded buffer",
      "Semaphore (C++20 counting_semaphore)", "Binary semaphore",
      "Barrier (C++20 std::barrier)", "Latch (C++20 std::latch)",
      "Spinlock implementation", "Ticket spinlock",
      "MCS lock concept", "CLH lock concept",
      "Atomic types (std::atomic<T>)", "fetch_add / fetch_sub",
      "compare_exchange_strong / weak", "load / store memory orders",
      "Memory order: relaxed, acquire, release, acq_rel, seq_cst", "Happens-before relation",
      "Synchronizes-with relation", "Data race definition",
      "Double-checked locking (broken vs fixed)", "Singleton with atomic",
      "Seqlock concept", "RCU (read-copy-update) concept",
      "Lock-free stack (Treiber)", "Lock-free queue (Michael-Scott)",
      "ABA problem", "ABA with tagged pointer",
      "Hazard pointers concept", "Epoch-based reclamation",
      "Thread pool implementation", "Task queue",
      "Work stealing deque", "std::async",
      "std::future / std::promise", "std::packaged_task",
      "std::shared_future", "Chaining futures",
      "Continuation passing", "coroutine + future combo",
      "Parallel algorithms (std::execution::par)", "Parallel for_each",
      "Parallel transform", "Parallel sort (parallel::sort)",
      "Parallel reduce", "Vector SIMD concept",
      "OpenMP basics (#pragma omp parallel)", "OpenMP reduction clause",
      "OpenMP schedule clause", "OpenMP tasks",
      "MPI concept (distributed memory)", "Message passing model",
      "Process vs thread", "Green threads concept",
      "Fibers (stackful coroutines)", "Boost.Fiber concept",
      "C++20 coroutines (co_await/co_yield/co_return)", "Coroutine promise type",
      "Coroutine handle", "Awaitable type",
      "Generator coroutine", "Async generator",
      "Task coroutine type", "Recursive coroutine",
      "Coroutine scheduler", "io_uring concept",
      "IOCP concept (Windows)", "Asio (Boost/standalone) basics",
      "Asio io_context", "Asio async_read / async_write",
      "Strand for thread safety in Asio", "Asio coroutines",
      "False sharing (cache line)", "Padding to avoid false sharing",
      "NUMA awareness", "Thread affinity",
      "CPU pinning", "Memory fence",
      "Sequentially consistent fences", "Dekker's algorithm",
      "Peterson's algorithm", "Lamport's bakery algorithm",
      "Fischer's algorithm", "Ticket lock",
      "Readers-writers problem variants", "Dining philosophers",
      "Sleeping barber problem", "Cigarette smokers problem",
      "Santa Claus problem", "Bank account thread-safe class",
      "Thread-safe singleton", "Thread-safe queue STL",
      "Thread-safe stack", "Thread-safe LRU cache",
      "Concurrent hash map concept", "Folly ConcurrentHashMap",
      "Thread sanitizer (TSan) usage", "Helgrind (Valgrind)",
      "DRD (Valgrind)", "Perf stat for multi-thread",
    ],
  },

  // ─── LEVEL 8 ───
  {
    level: 8,
    id: "c80",
    name: "Advanced Algorithms (String, Math, Number Theory)",
    count: 130,
    problems: [
      // String algorithms
      "KMP pattern matching", "KMP prefix function",
      "Z-function pattern matching", "Rabin-Karp multi-pattern",
      "Boyer-Moore bad-char heuristic", "Boyer-Moore good-suffix",
      "Aho-Corasick multi-string search", "Aho-Corasick on stream",
      "Suffix array (SA-IS O(n))", "Suffix array (O(n log n) DC3 / Skew)",
      "LCP array Kasai's algorithm", "LCP array sparse table",
      "Longest repeated substring", "Longest common substring (SA)",
      "Count distinct substrings (SA)", "Lexicographically smallest rotation",
      "String period (KMP)", "Shortest pattern with period",
      "Longest palindrome (Manacher's)", "Palindromic substrings count",
      "eertree / palindrome tree", "Suffix automaton (SAM) build",
      "SAM longest common substring", "SAM count substrings",
      "SAM endpos sets", "Online string matching",
      // Number theory
      "Sieve of Eratosthenes optimized", "Linear sieve (Euler's sieve)",
      "Segmented sieve", "Bitset sieve",
      "Trial division factorization", "Pollard's rho factorization",
      "Miller-Rabin primality test (deterministic)", "Lucas primality test",
      "Fermat's little theorem", "Euler's theorem",
      "Modular exponentiation (fast)", "Modular inverse (Fermat)",
      "Modular inverse (extended GCD)", "Extended Euclidean algorithm",
      "Chinese Remainder Theorem (CRT)", "Garner's algorithm",
      "Euler's totient function", "Totient sieve",
      "Möbius function", "Möbius inversion",
      "Dirichlet convolution", "Multiplicative functions",
      "Sum of divisors (sigma)", "Number of divisors (tau)",
      "Liouville function", "Von Mangoldt function",
      "Primitive root modulo p", "Discrete logarithm (Baby-step Giant-step)",
      "Pohlig-Hellman algorithm", "Index calculus concept",
      "Legendre symbol", "Jacobi symbol",
      "Quadratic reciprocity", "Tonelli-Shanks sqrt mod p",
      "Cipolla's algorithm", "Lucas sequences",
      "Pell's equation", "Continued fractions",
      "Stern-Brocot tree", "Farey sequence",
      "Egyptian fractions", "Zeckendorf representation",
      "Wilson's theorem", "Bertrand's postulate",
      "Prime gaps", "Twin primes",
      "Sophie Germain primes", "Safe primes",
      "Mersenne primes", "Fermat primes",
      "Goldbach conjecture (verification)", "Waring's problem",
      // Combinatorics & generating functions
      "Binomial coefficients (Pascal's triangle)", "nCr mod p (Lucas' theorem)",
      "nCr mod prime (precompute factorial)", "Catalan number formula",
      "Catalan applications (all 14)", "Stirling numbers 1st/2nd kind",
      "Bell numbers (partition)", "Bernoulli numbers",
      "Euler numbers", "Derangements formula D(n)",
      "Inclusion-exclusion principle", "Principle of inclusion-exclusion problems",
      "Burnside's lemma (Polya counting)", "Polya enumeration theorem",
      "Necklace counting", "Bracelet counting",
      "Lindström-Gessel-Viennot lemma", "Lattice path counting",
      "Generating functions basics", "OGF for sequences",
      "EGF (exponential generating functions)", "GF for Fibonacci",
      "Formal power series (addition, mult)", "Polynomial multiplication (naive)",
      // FFT & Polynomial
      "DFT/IDFT basics", "FFT (Cooley-Tukey radix-2)",
      "FFT iterative (bit-reversal permutation)", "FFT for polynomial multiplication",
      "NTT (Number Theoretic Transform)", "NTT prime choice",
      "NTT inverse", "Karatsuba multiplication",
      "Polynomial inverse (Newton's method)", "Polynomial sqrt",
      "Polynomial exp / log", "Polynomial GCD",
      "Polynomial evaluation multi-point", "Polynomial interpolation",
      "Lagrange interpolation", "Newton's forward difference",
      "Berlekamp-Massey algorithm", "Linear recurrence via matrix expo",
      "Berlekamp-Massey + Kitamasa", "Berlekamp-Massey BM+BM",
    ],
  },
  {
    level: 8,
    id: "c81",
    name: "System Design & Low-Level C++",
    count: 120,
    problems: [
      // Memory & systems
      "Virtual memory basics", "Page table concept",
      "TLB and cache concept", "Cache hierarchy (L1/L2/L3)",
      "Cache miss types (cold, capacity, conflict)", "MESI cache coherence protocol",
      "False sharing (cache line collision)", "NUMA architecture",
      "Memory barriers (fence instructions)", "Load-store reordering",
      "Store buffer / invalidation queue", "Sequential consistency model",
      "Total store order (TSO) x86", "ARM relaxed memory model",
      "C++ memory model formal", "Data-race-free programs",
      // Process & OS
      "Process vs thread creation cost", "Context switch overhead",
      "User-mode vs kernel-mode", "System calls overhead",
      "mmap vs malloc", "huge pages",
      "Copy-on-write pages", "Demand paging",
      "POSIX signals", "Signal handlers in C++",
      "Async-signal-safe functions", "Fork + exec pattern",
      "Zombie process", "Orphan process",
      "Shared memory (POSIX shm)", "Message queues (POSIX mq)",
      "Named/unnamed pipes", "Unix domain sockets",
      "TCP/IP socket programming", "Blocking vs non-blocking socket",
      "select / poll / epoll", "kqueue (macOS/BSD)",
      "io_uring (Linux 5.1+)", "Event loop pattern",
      "Reactor vs Proactor pattern", "IOCP (Windows)",
      // Compiler & linking
      "Compilation pipeline (cpp→asm→obj→exe)", "ELF binary format",
      "GOT and PLT (dynamic linking)", "Position-independent code (PIC)",
      "ASLR (address space layout randomization)", "Stack canary",
      "Stack frames and calling conventions", "x86-64 calling convention",
      "ARM AAPCS calling convention", "Inline assembly basics",
      "Compiler intrinsics (SSE/AVX)", "SIMD vectorization",
      "Auto-vectorization flags", "Loop unrolling pragma",
      "Profile-guided optimization (PGO)", "Link-time optimization (LTO)",
      "Devirtualization", "Inlining decision heuristics",
      "Constexpr evaluation at compile time", "Constant folding",
      "Dead code elimination", "Alias analysis",
      // ABI & interop
      "C++ ABI (Itanium)", "Name mangling rules",
      "vtable ABI layout", "RTTI layout",
      "dynamic_cast ABI", "Exception handling ABI (zero-cost)",
      "Landing pads and call-site tables", "Unwind tables (.eh_frame)",
      "C interop (extern C)", "C++ from Python (ctypes/cffi)",
      "Python bindings (pybind11)", "Node.js native addon (N-API)",
      "JNI (Java Native Interface)", "Rust FFI with C++",
      // Performance engineering
      "Profiling: gprof, perf, VTune", "Flame graphs interpretation",
      "PMU hardware counters", "IPC (instructions per cycle)",
      "Branch misprediction cost", "Speculative execution",
      "Meltdown / Spectre mitigations", "Prefetching strategies",
      "Cache-oblivious algorithms", "Memory pool design",
      "Slab allocator", "jemalloc / tcmalloc internals",
      "Huge page allocation", "Transparent huge pages",
      "Memory-mapped files", "Zero-copy networking",
      "sendfile() system call", "DMA concept",
      "Lock-free data structures theory", "Wait-free progress",
      "Obstruction-free progress", "Non-blocking I/O with epoll",
      "Asynchronous I/O (AIO)", "libuv event loop concept",
      "Node.js under the hood", "V8 JIT concept",
      "JVM vs native code", "GC pause vs deterministic",
      "Real-time C++ constraints", "Deterministic latency",
      "High-frequency trading C++", "FPGA programming concept",
      "Embedded C++ (no exceptions/RTTI)", "freestanding C++",
      "Kernel module C++ (restricted env)", "CUDA C++ basics",
    ],
  },

  // ─── LEVEL 9 ───
  {
    level: 9,
    id: "c90",
    name: "Competitive Programming Mastery",
    count: 150,
    problems: [
      // Techniques
      "Mo's algorithm offline range queries", "Mo's with updates",
      "Mo's on trees", "Sqrt decomposition (blocks)",
      "Sqrt decomp range queries", "Heavy path decomp advanced",
      "Centroid decomp advanced problems", "DSU on tree sack",
      "Virtual tree construction", "Auxiliary tree queries",
      "Offline LCA (Tarjan union-find)", "Parallel binary search",
      "CDQ divide and conquer (offline 3D)", "Slope trick optimization",
      "Aliens trick (lambda optimization)", "SMAWK algorithm",
      "Divide and conquer DP optimization", "Convex hull trick (CHT)",
      "Li Chao tree (line container)", "Kinetic heaps concept",
      // DP advanced
      "DP profile (broken profile / plug DP)", "Digit DP advanced",
      "DP on strings (palindromes advanced)", "DP on trees advanced",
      "DP on graphs (shortest path gadgets)", "DP with convex hull trick",
      "DP with monotone queue", "DP SOS (sum over subsets)",
      "Subset DP (bitmask all subsets)", "SOS DP O(n·2^n)",
      "DP on matroid intersection concept", "DP knuth optimization",
      "Knuth-Yao speedup", "Hirschberg space-opt LCS",
      "Four Russians method", "Divide and conquer LCS",
      // Geometry
      "Computational geometry primitives", "Cross product sign",
      "Point in polygon (ray casting)", "Convex hull Graham scan",
      "Convex hull Andrew monotone chain", "Jarvis march",
      "Convex hull trick rotating calipers", "Diameter of convex polygon",
      "Closest pair of points (divide & conquer)", "Voronoi diagram concept",
      "Delaunay triangulation concept", "Line sweep algorithm",
      "Area of union of rectangles", "Area of union of circles",
      "Half-plane intersection", "Minkowski sum",
      "Rotating calipers technique", "Point location in triangulation",
      "Segment intersection (Bentley-Ottmann)", "Shamos-Hoey algorithm",
      "K-d tree (range queries 2D)", "Range tree",
      "Interval tree queries", "Orthogonal range searching",
      "Fractional cascading advanced", "Persistent data structures",
      // Game theory
      "Sprague-Grundy theorem", "Nimber computation",
      "Nim game variants", "Staircase Nim",
      "Wythoff's Nim", "Grundy values for Kayles",
      "Grundy values for Turning Turtles", "Green hackenbush",
      "Blue-red hackenbush", "Surreal numbers concept",
      "Alpha-beta pruning", "Minimax with memoization",
      "Retrograde analysis", "Endgame tablebase concept",
      // Linear algebra
      "Matrix exponentiation O(k³ log n)", "Fibonacci matrix expo",
      "Counting paths of length n", "Linear recurrence kitamasa",
      "Gaussian elimination over GF(2)", "XOR basis (linear basis)",
      "Rank of matrix over GF(2)", "Berlekamp-Massey + matrix expo",
      "Gaussian elimination floating point", "LU decomposition",
      "QR decomposition concept", "Eigenvalues concept",
      "Eigenvalue power iteration", "PageRank concept",
      "Markov chains in CP", "Expected value DP",
      "Probability DP advanced", "Linearity of expectation tricks",
      // Flow advanced
      "Project selection (min cut)", "Closure problem (max flow)",
      "MCMF minimum cost matching", "Min cost flow with negative cycles",
      "MCMF for assignment", "Minimum weight closure",
      "Hall's condition checking", "Max flow decomposition",
      "Gomory-Hu tree", "Gomory-Hu cut tree",
      "Parametric max flow", "Undirected global min cut (Stoer-Wagner)",
      "Randomized min cut (Karger's)", "Isolating cuts technique",
      // Randomized algorithms
      "Las Vegas vs Monte Carlo", "Randomized quick select",
      "Randomized quick sort analysis", "Treap randomized",
      "Skip list probabilistic analysis", "Bloom filter false positive rate",
      "Count-min sketch error analysis", "Miller-Rabin error probability",
      "Schwartz-Zippel lemma", "Freivalds algorithm",
      "Hashing-based de-duplicates", "Locality-sensitive hashing concept",
      "Random sampling reservoir", "Random graph properties",
      "Lovász Local Lemma concept", "Expander graphs concept",
    ],
  },

  // ─── LEVEL 10 ───
  {
    level: 10,
    id: "c100",
    name: "Expert / Research-Level C++ & CS",
    count: 120,
    problems: [
      // C++ standardization & future
      "C++23 features overview", "C++26 planned features",
      "Reflection TS proposal", "Static reflection (metaclasses)",
      "Pattern matching (P1371)", "Executors (P2300)",
      "Sender/receiver model", "std::execution networking",
      "Contracts (P2521)", "Precondition / postcondition",
      "Invariant syntax", "Profiles (safety profiles proposal)",
      "Carbon language interop", "Circle C++ extension",
      "Val language ideas", "Safe C++ subset",
      // Category theory in FP/C++
      "Functor concept (map)", "Monad concept (bind/flatMap)",
      "Applicative functor", "Monoid in C++ (fold)",
      "Free monad concept", "Cont monad (continuation)",
      "Comonad concept", "Arrows in FP",
      "Lens optics in C++", "Prism optics",
      "Profunctor optics", "Zippers in C++",
      // Formal verification
      "Hoare logic basics", "Floyd-Hoare triples",
      "Weakest precondition", "Loop invariant formal proof",
      "Separation logic concept", "Concurrent separation logic",
      "Model checking (SPIN, TLA+)", "TLA+ spec for C++ system",
      "SMT solvers (Z3) usage", "CBMC model checker",
      "Frama-C analysis", "MISRA C++ compliance",
      "Undefined behavior formal semantics", "CompCert verified compiler concept",
      // Compiler internals
      "LLVM IR basics", "LLVM pass writing",
      "Clang AST traversal", "LibTooling basics",
      "Clang-Tidy check writing", "MLIR dialect concept",
      "GCC GIMPLE IR", "GCC RTIL IR",
      "SSA form", "Phi nodes",
      "Dominator tree", "Dominator frontier",
      "Control flow graph", "Liveness analysis",
      "Register allocation (coloring)", "Instruction selection",
      "Instruction scheduling", "Peephole optimization",
      "Loop-invariant code motion", "Strength reduction",
      "Vectorization analysis", "Polyhedral model",
      // Distributed systems
      "CAP theorem formal", "PACELC theorem",
      "Paxos consensus algorithm", "Multi-Paxos",
      "Raft consensus", "Raft leader election",
      "Raft log replication", "Raft snapshots",
      "Zab (Zookeeper) protocol", "Viewstamped replication",
      "Byzantine fault tolerance (PBFT)", "Tendermint BFT",
      "Linearizability formal definition", "Sequential consistency",
      "Eventual consistency", "CRDT (Conflict-free Replicated Data Types)",
      "G-counter, PN-counter CRDT", "OR-set CRDT",
      "Vector clocks", "Lamport clocks",
      "Hybrid logical clocks", "Google Spanner TrueTime",
      "Calvin deterministic DB", "CockroachDB MVCC",
      "LSM tree (LevelDB / RocksDB)", "B-tree vs LSM trade-offs",
      // OS / kernel concepts
      "Custom memory allocator for OS", "Lock-free OS data structures",
      "Seqlock in kernel", "RCU in Linux kernel",
      "Futex implementation", "Priority inheritance mutex",
      "Real-time scheduling (POSIX RT)", "WCET analysis",
      "Interrupt latency", "DPC / softirq",
      "NUMA memory policy", "cgroups and memory limits",
      "seccomp sandboxing from C++", "eBPF from C++",
      "XDP (eXpress Data Path)", "DPDK (Data Plane Dev Kit) concept",
      "RDMA programming concept", "Zero-copy RDMA verbs",
      "SmartNIC offloading", "P4 programmable networks concept",
    ],
  },
];

const totalProblems = allCategories.reduce((s, c) => s + c.count, 0);

export default function App() {
  const [selectedLevel, setSelectedLevel] = useState(null);
  const [expandedCat, setExpandedCat] = useState(null);

  const visibleCategories =
    selectedLevel === null
      ? allCategories
      : allCategories.filter((c) => c.level === selectedLevel);

  const getLevelInfo = (lvl) => levels.find((l) => l.id === lvl);

  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0f", color: "#e2e8f0", fontFamily: "'JetBrains Mono', 'Fira Code', monospace" }}>
      {/* Header */}
      <div style={{ background: "linear-gradient(135deg, #0f0f1a 0%, #1a0a2e 50%, #0a1a0f 100%)", borderBottom: "1px solid #1e293b", padding: "2rem 1.5rem 1.5rem" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "0.5rem" }}>
            <span style={{ fontSize: "2rem" }}>⚡</span>
            <h1 style={{ margin: 0, fontSize: "1.6rem", fontWeight: 800, background: "linear-gradient(90deg, #4ade80, #38bdf8, #c084fc)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>
              C++ Interview Prep — Master Roadmap
            </h1>
          </div>
          <p style={{ margin: 0, color: "#64748b", fontSize: "0.85rem" }}>
            {allCategories.length} categories · <span style={{ color: "#4ade80", fontWeight: 700 }}>{totalProblems.toLocaleString()}+ problems</span> · Level 0 → Level 10
          </p>
        </div>
      </div>

      {/* Level selector */}
      <div style={{ background: "#0d0d1a", borderBottom: "1px solid #1e293b", padding: "1rem 1.5rem", overflowX: "auto" }}>
        <div style={{ maxWidth: 1100, margin: "0 auto", display: "flex", gap: "0.4rem", flexWrap: "wrap" }}>
          <button
            onClick={() => setSelectedLevel(null)}
            style={{
              padding: "0.35rem 0.9rem", borderRadius: 6, border: "none", cursor: "pointer", fontSize: "0.75rem", fontFamily: "inherit", fontWeight: 700,
              background: selectedLevel === null ? "#4ade80" : "#1e293b",
              color: selectedLevel === null ? "#000" : "#94a3b8",
              transition: "all 0.15s"
            }}>ALL</button>
          {levels.map((lvl) => (
            <button
              key={lvl.id}
              onClick={() => setSelectedLevel(selectedLevel === lvl.id ? null : lvl.id)}
              style={{
                padding: "0.35rem 0.75rem", borderRadius: 6, border: `1px solid ${selectedLevel === lvl.id ? lvl.color : "transparent"}`,
                cursor: "pointer", fontSize: "0.72rem", fontFamily: "inherit", fontWeight: 700,
                background: selectedLevel === lvl.id ? lvl.bg : "#1a1a2e",
                color: selectedLevel === lvl.id ? lvl.color : "#64748b",
                transition: "all 0.15s"
              }}>
              L{lvl.id} · {lvl.title}
            </button>
          ))}
        </div>
      </div>

      {/* Categories grid */}
      <div style={{ maxWidth: 1100, margin: "0 auto", padding: "1.5rem" }}>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))", gap: "1rem" }}>
          {visibleCategories.map((cat) => {
            const lvl = getLevelInfo(cat.level);
            const isOpen = expandedCat === cat.id;
            return (
              <div key={cat.id} style={{
                background: "#0f0f1a", border: `1px solid ${isOpen ? lvl.color : "#1e293b"}`,
                borderRadius: 10, overflow: "hidden", transition: "border-color 0.2s",
                boxShadow: isOpen ? `0 0 20px ${lvl.color}22` : "none"
              }}>
                {/* Card header */}
                <div
                  onClick={() => setExpandedCat(isOpen ? null : cat.id)}
                  style={{ padding: "1rem", cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: "0.75rem" }}
                >
                  <div style={{ flex: 1 }}>
                    <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.4rem" }}>
                      <span style={{ fontSize: "0.65rem", fontWeight: 800, padding: "0.15rem 0.5rem", borderRadius: 4, background: lvl.bg, color: lvl.color, border: `1px solid ${lvl.color}44` }}>
                        {lvl.label}
                      </span>
                      <span style={{ fontSize: "0.65rem", color: "#475569" }}>{lvl.title}</span>
                    </div>
                    <h3 style={{ margin: 0, fontSize: "0.9rem", fontWeight: 700, color: "#e2e8f0", lineHeight: 1.3 }}>{cat.name}</h3>
                    <div style={{ marginTop: "0.5rem", display: "flex", alignItems: "center", gap: "0.75rem" }}>
                      <span style={{ fontSize: "0.75rem", color: lvl.color, fontWeight: 700 }}>{cat.count}+ problems</span>
                    </div>
                    {/* Mini progress bar */}
                    <div style={{ marginTop: "0.5rem", height: 3, background: "#1e293b", borderRadius: 2 }}>
                      <div style={{ width: `${Math.min(100, (cat.count / 150) * 100)}%`, height: "100%", background: lvl.color, borderRadius: 2 }} />
                    </div>
                  </div>
                  <span style={{ color: lvl.color, fontSize: "1rem", marginTop: "0.1rem" }}>{isOpen ? "▲" : "▼"}</span>
                </div>

                {/* Expanded problem list */}
                {isOpen && (
                  <div style={{ borderTop: `1px solid ${lvl.color}33`, padding: "0.75rem 1rem 1rem", maxHeight: 380, overflowY: "auto" }}>
                    <p style={{ margin: "0 0 0.6rem", fontSize: "0.7rem", color: "#475569" }}>
                      Showing {cat.problems.length} of {cat.count}+ problems:
                    </p>
                    <div style={{ display: "grid", gap: "0.25rem" }}>
                      {cat.problems.map((p, i) => (
                        <div key={i} style={{ display: "flex", gap: "0.5rem", alignItems: "flex-start" }}>
                          <span style={{ color: lvl.color, fontSize: "0.65rem", marginTop: "0.1rem", minWidth: 14 }}>▸</span>
                          <span style={{ fontSize: "0.75rem", color: "#94a3b8", lineHeight: 1.4 }}>{p}</span>
                        </div>
                      ))}
                      {cat.count > cat.problems.length && (
                        <div style={{ marginTop: "0.5rem", padding: "0.4rem 0.6rem", background: lvl.bg, borderRadius: 6, textAlign: "center" }}>
                          <span style={{ fontSize: "0.7rem", color: lvl.color }}>+ {cat.count - cat.problems.length} more problems in full roadmap</span>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Summary footer */}
        <div style={{ marginTop: "2rem", padding: "1.25rem", background: "#0f0f1a", border: "1px solid #1e293b", borderRadius: 10 }}>
          <h3 style={{ margin: "0 0 1rem", fontSize: "0.9rem", color: "#94a3b8" }}>📊 Roadmap Summary</h3>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: "0.5rem" }}>
            {levels.map((lvl) => {
              const cats = allCategories.filter((c) => c.level === lvl.id);
              const total = cats.reduce((s, c) => s + c.count, 0);
              return (
                <div key={lvl.id} style={{ padding: "0.6rem 0.75rem", background: lvl.bg, border: `1px solid ${lvl.color}33`, borderRadius: 8 }}>
                  <div style={{ fontSize: "0.7rem", fontWeight: 700, color: lvl.color }}>{lvl.label} · {lvl.title}</div>
                  <div style={{ fontSize: "0.72rem", color: "#94a3b8", marginTop: "0.25rem" }}>
                    {cats.length} {cats.length === 1 ? "category" : "categories"} · {total.toLocaleString()}+ problems
                  </div>
                </div>
              );
            })}
            <div style={{ padding: "0.6rem 0.75rem", background: "#1a1a2e", border: "1px solid #334155", borderRadius: 8 }}>
              <div style={{ fontSize: "0.7rem", fontWeight: 700, color: "#f8fafc" }}>TOTAL</div>
              <div style={{ fontSize: "0.72rem", color: "#4ade80", marginTop: "0.25rem", fontWeight: 700 }}>
                {allCategories.length} categories · {totalProblems.toLocaleString()}+ problems
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
